FILENAME="entrrada.csv"
AVAILABLE_KEYS=['Call type','Date','Time','Carrier connect date','Carrier connect time','Carrier elapsed time','Sensor_Type','Sensor_ID','Recording Office_Type','Recording Office_ID',
                'Timing indicator','Study indicator','Service observed / Traffic sampled','Operator action','Service feature code','Overseas indicator','IC / INC indicator','IC/INC call event status','IC / INC Routing Indicator','Dialing and presubscription indicator', 'ANI / CPN indicator']
MINUTES=60
MILLISECONDS=1000
CODE_LOCAL_MESSAGE=5
NAME_LOCAL_MESSAGE="Local message rate call"
CODE_INTERLATA=110
NAME_INTERLATA="Interlata call"
CODE_INCOMING_CDR=119
NAME_INCOMING_CDR="Incoming CDR"
COLUMN_TYPE="type"
COLUMN_CALL_TYPE="Call type"
COLUMN_ELAPSED_TIME="elapsedtime"
COLUMN_LENGTH_CALL="Length of call"
COLUMN_TRUNK_IRI="Trunk Identification_Routing Indicator"
COLUMN_TRUNK_IGN="Trunk Identification_Trunk Group Number"
COLUMN_TRUNK_ITM="Trunk Identification_Trunk Member Number"
COLUMN_ORIGIN_NPA="originatingnpa"
COLUMN_ORIGIN_NUMBER="originatingnumber"
COLUMN_TERMINATING_NPA="terminatingnpa"
COLUMN_TERMINATING_NUMBER="terminatingnumber"
COLUMN_CALLING_NUMBER="Calling number"
COLUMN_CALLED_NUMBER="Called number"
COLUMN_M119_TRUNK_GROUP_INFO="m119.trunkgroupinfo"
COLUMN_M104_TRUNK0_ID="m104.trunkid"
COLUMN_M104_TRUNK1_ID="m104.trunkid1"
COLUMN_TRUNK_GROUP_INTEROFFICE="Trunk Group_Trunk Group Number - Interoffice"
ID_PROPERTY="id"
NAME_PROPERTY="nombre"
NAN_VALUE="nan:nan:nan"
SEPARATOR="|"
OUTPUT_FILENAME='result.csv'
COLON=":"